name: Build and Push Docker Image

permissions:
  contents: read

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Sanitize Ref Name
        id: sanitize_ref_name
        uses: ./.github/actions/sanitize-ref-name
        with:
          ref-name: ${{ github.ref_name }}
          target: docker-tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set Docker Image Tag
        env:
          REF: ${{ github.ref }}
          REF_NAME: ${{ github.ref_name }}
          SANITIZED_REF_NAME: ${{ steps.sanitize_ref_name.outputs.sanitized-ref-name }}
        # cSpell: ignore elif
        run: |
          TAG="latest"

          if [[ "$REF" == refs/tags/* ]]; then
            TAG="$REF_NAME"
          elif [[ "$REF" == "refs/heads/main" ]]; then
            TAG="latest"
          elif [[ "$REF" == refs/heads/* ]]; then
            TAG="$SANITIZED_REF_NAME"
          fi

          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: donniean/react-app:${{ env.TAG }}
          push: true
